name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  schedule:
      - cron: '0 0 * * 0'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: x86_64-apple-darwin
            os: macos-12
          - target: x86_64-pc-windows-msvc
            os: windows-2022
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Julia environment
      uses: julia-actions/setup-julia@v1.9.2
      with:
        version: '1.0'
    - name: Cache Julia artifacts
      uses: julia-actions/cache@v1.2.2
      with:
        cache-registries: 'true'
    - name: Build a package
      uses: julia-actions/julia-buildpkg@v1.4.2
    - name: Run tests
      uses: julia-actions/julia-runtest@v1.9.3

  fmt:
    name: Format
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Julia environment
      uses: julia-actions/setup-julia@v1.9.2
      with:
        version: '1.0'
    - name: Cache Julia artifacts
      uses: julia-actions/cache@v1.2.2
      with:
        cache-registries: 'true'
    - name: Check code formatted
      run: |
        julia -e 'using Pkg; Pkg.add("JuliaFormatter")'
        julia -e 'using JuliaFormatter; JuliaFormatter.format(".", verbose = true)'
        git diff --exit-code
