# SPDX-FileCopyrightText: 2023 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: CI

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "main"
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os-alias:
          - ubuntu
          - macos
          - windows
        version-alias:
          - minimum
          - latest
        include:
          - os-alias: ubuntu
            os: ubuntu-24.04
          - os-alias: macos
            os: macos-15
          - os-alias: windows
            os: windows-2025
          - version-alias: minimum
            version: "1.0"
          - version-alias: latest
            version: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3
      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v3.0.1
        with:
          version: ${{ matrix.version }}
          arch: ${{ (matrix.os-alias == 'macos' && matrix.version-alias == 'latest') && 'aarch64' || 'x64' }}
          force-arch: ${{ (matrix.os-alias == 'macos' && matrix.version-alias == 'minimum') && 'true' || 'false' }}
      - name: Build a package
        uses: julia-actions/julia-buildpkg@v1.7.0
      - name: Run tests
        uses: julia-actions/julia-runtest@v1.11.4

  fmt:
    name: Format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3
      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v3.0.1
        with:
          version: "1" # automatically expands to the latest stable release of Julia
      - name: Run formatter in check mode
        run: |
          julia -e 'using Pkg; Pkg.add("JuliaFormatter")'
          julia -e 'using JuliaFormatter; JuliaFormatter.format(".", verbose = true)'
          git diff --exit-code

  prettier:
    name: Prettier
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3
      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Run formatter in check mode
        run: npx prettier -c "**.{md,yaml,yml}"
