# SPDX-FileCopyrightText: 2023 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: CI

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "master"
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-14
          - windows-2022
        version:
          - "1.0" # minimum supported Julia version
          - "1" # automatically expands to the latest stable release of Julia
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v2.2.0
        with:
          version: ${{ matrix.version }}
          arch: "x64"
      - name: Build a package
        uses: julia-actions/julia-buildpkg@v1.6.0
      - name: Run tests
        uses: julia-actions/julia-runtest@v1.10.0

  fmt:
    name: Format
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v2.2.0
        with:
          version: "1" # automatically expands to the latest stable release of Julia
      - name: Check code formatted
        run: |
          julia -e 'using Pkg; Pkg.add("JuliaFormatter")'
          julia -e 'using JuliaFormatter; JuliaFormatter.format(".", verbose = true)'
          git diff --exit-code
