# SPDX-FileCopyrightText: 2023 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: Deployment

on:
  pull_request:
  push:
    branches:
      - "develop"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v2.3.0
        with:
          version: "1" # automatically expands to the latest stable release of Julia
      - name: Build a package
        uses: julia-actions/julia-buildpkg@v1.6.0
      - name: Deploy
        uses: julia-actions/julia-docdeploy@v1.3.1
        if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
