# SPDX-FileCopyrightText: 2023 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: Deployment

on:
  push:
    branches:
      - develop
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    name: Deploy
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v1.9.2
        with:
          version: "1.9"
      - name: Cache Julia artifacts
        uses: julia-actions/cache@v1.2.2
        with:
          cache-registries: "true"
      - name: Build a package
        uses: julia-actions/julia-buildpkg@v1.4.2
      - name: Deploy
        uses: julia-actions/julia-docdeploy@v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
